### ISSUE TITLE
Gradle sync failed: Software caused connection abort: recv failed

### ISSUE THREAD

**Issue by venshine** [msdx/gradle-publish#10]
加入`apply from: 'https://raw.githubusercontent.com/msdx/gradle-publish/master/bintray.gradle'`代码后，gradle sync出错。
错误提示：
Gradle sync failed: Software caused connection abort: recv failed

**Comment by msdx** [comment]
网络问题

**Comment by venshine** [comment]
有没有可能地址被墙了，需要翻墙？

**Comment by msdx** [comment]
建议你把脚本复制到你的项目中。
