### ISSUE TITLE
Error:No such property: archivesBaseName for class: org.gradle.api.internal.project.DefaultProject_Decorated

### ISSUE THREAD

**Issue by ouyangzn** [msdx/gradle-publish#12]
build时报错：
Error:No such property: archivesBaseName for class: org.gradle.api.internal.project.DefaultProject_Decorated

**Comment by msdx** [comment]
你的gradle版本和`com.android.tools.build:gradle`版本分别是什么？

**Comment by ouyangzn** [comment]
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'

classpath 'com.android.tools.build:gradle:2.1.0'

**Comment by msdx** [comment]
@ouyangzn 请问你的gradle版本是？
查看gradle版本：
如果你使用的是本机gradle，可通过命令`gradle -version`来查看。如果使用的是gradlew，可查看项目根目录下的gradle/gradle-wrapper.properties，或通过`./gradlew -version`（windows用户请使用`gradlew -version`）来查看

**Comment by ouyangzn** [comment]
是用的2.10的
![qq 20160912173055](https://cloud.githubusercontent.com/assets/8808376/18431259/c31c94a8-790e-11e6-9792-f1033b9a6f11.png)

**Comment by msdx** [comment]
@ouyangzn 请问你是不是把`apply from: 'bintray.gradle'`之类的语句放在了`apply plugin: 'com.android.library'`的前面？如果是，请把应用脚本配置的这一行，放在build.gradle的最后。可参考该项目脚本 ：https://github.com/msdx/status-bar-compat/blob/master/library/build.gradle

**Comment by msdx** [comment]
@ouyangzn 当前版本的脚本由于使用到了`project.archivesBaseName`属性，该属性在`com.android.library`插件中定义，所以需要把应用脚本配置的这一行放在后面。

**Comment by ouyangzn** [comment]
我是写在app 的build.gradle里面的，不是写在用来发布的那个module的build.gradle里面,不知道是不是写错了位置+_+。 不过我已经找到另外的方法发布成功了，所以不用太纠结这个问题，还是谢啦，顺带问一下你是从哪找的发布的资料的，我都是搜发布到jcenter教程，搞了好久才成功，没看到一个官方的教程

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:2.1.0'
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
    // 提交到jcenter使用的插件：
    classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
    classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'
    // Remove it if you won't to publish SNAPSHOT version.
    classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.0.0"

  }
}
// this script was used to upload files to bintray.
//apply from: 'BaseRecyclerViewAdapter/bintray.gradle'

allprojects {
  repositories {
    jcenter()
  }
}

task clean(type: Delete) {
  delete rootProject.buildDir
}
```

**Comment by msdx** [comment]
你需要把它写在`apply plugin: 'com.android.library'`之后，这是因为这个脚本前面有个属性是用到了这个插件定义的project类里的对象。如果你在它之前就apply，就会出这个问题，这也是在本项目的README就提到的需要放它放在library项目的build.gradle文件的底部的原因。这个问题原因和解决方式我已经找到，我不纠结。不过经过这个issue，我已经在README.md上加粗相关注意事件，并且也在build.gradle示例文件中加上相关注释。
发布到jcenter的教程的话，我以前也是鼓捣了几个晚上。最初成功是参考bintray文档，然后stackoverflow，再找github上有发布到jcenter的项目看他们的代码，然后写自己的发布脚本，不过没有正确地解决传递依赖的问题。目前的这个脚本是参考同在一个公司的师兄的一个项目的。

**Comment by ouyangzn** [comment]
好的，大概明白原因了，最后还有个问题：
你在bintray上是不是建了一个叫maven的Repositories？之前发布一直说：HTTP/1.1 404 Not Found [message:Repo 'maven' was not found]

```
bintray {
    user = project.hasProperty('bintrayUser') ? project.property('bintrayUser') : project.property('BINTRAY_USER')
    key = project.hasProperty('bintrayKey') ? project.property('bintrayKey') : project.property('BINTRAY_KEY')

    configurations = ['archives']

    dryRun = false
    publish = true

    pkg {
        repo = 'maven' // ------仓库名-----
        name = PROJ_NAME
        licenses = ['Apache-2.0']
        vcsUrl = PROJ_VCSURL
        websiteUrl = PROJ_WEBSITEURL
        issueTrackerUrl = PROJ_ISSUETRACKERURL
        publicDownloadNumbers = true
        version {
            name = PROJ_VERSION
            desc = PROJ_DESCRIPTION
            vcsTag = PROJ_VERSION

            gpg {
                sign = true
            }
        }
    }
}
```

搞了好久，后来在stackovewflow上刚好有另外一个哥们也是这问题，然后他自己解决了，告诉了我，说那个repo是指在bintray上的仓库名

**Comment by msdx** [comment]
好像是吧，几年前弄的了。那时候好像在bintray上有多个repo可以传，有maven, Generic, rpm等。是不是要手动创建我就忘了

**Comment by ouyangzn** [comment]
貌似现在需要自己创建了，我不去创建，就报那个404，然后自己去创建了一个仓库，填上自己的仓库名就好了，可以把这个问题在readme写一下。OK，现在没什么问题了，谢啦

**Comment by msdx** [comment]
@ouyangzn 我抽时间再调整完善一下，也欢迎你提PR帮助改善提升。

**Comment by imknown** [comment]
Okay, resolved by myself... **DO NOT** use `archivesBaseName` in `groovy static statements`...
