### ISSUE TITLE
引用脚本部分可以修改得更方便

### ISSUE THREAD

**Issue by hangox** [msdx/gradle-publish#13]
可以修改为以下这个样子，就不用手动下载脚本了，gradle 会自动下载脚本的

``` gradle
apply from : "https://raw.githubusercontent.com/msdx/gradle-publish/master/bintray.gradle"
```

**Comment by msdx** [comment]
建议下载脚本是为了这里更新的话以前的项目也不会影响到。

**Comment by hangox** [comment]
这个问题也不大，可以生成一个tag，使用tag的链接就好了，这样就算更改了代码，因为使用的是tag的，tag是不会变的

浩码农 notifications@github.com于2016年10月7日周五 下午5:50写道：

**Comment by msdx** [comment]
我对tag的理解必须是明确稳定不冗余的，在这里对我而言明显不合适。

**Comment by hangox** [comment]
你发布了一个稳定的脚本，理应添加一个tag，这个版本就是这样的了。当你修改为下一个版本的时候，就是另外一个tag了，这样并没有滥用tag

浩码农 notifications@github.com于2016年10月7日周五 下午11:07写道：

**Comment by msdx** [comment]
不再在这里推荐直接引用这里的链接是考虑过多种原因的，这里的维护是一个原因，github访问也是一个问题(不是所有的公司的ci服务器都会对github翻墙)，还有其他问题等，最后我才建议把文件拷下来的。

**Comment by msdx** [comment]
我不反对那样用，但不会在我这里推荐。

**Comment by hangox** [comment]
不好意识，冒犯了，可能思维方式的不一样吧。
我首先考虑的是这件事请值不值得做。一个链接解决脚本拷贝来拷贝去的问题，我觉得这件事情很值得做。值得做，我就会想解决这个问题。
1. 使用tag确定脚本的稳定性
2. github 并不是国内访问不了，只是域名解析偶尔性的失败而已，解决方案有很多，使用8.8.8.8 解析，或者直接使用CDN缓存。
3. 这不是二选一的方案，只是方案不同地方是会有不同的表现，应该给人更多的选择。

浩码农 notifications@github.com于2016年10月7日周五 下午11:16写道：

我不反对那样用，但不会在我这里推荐。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/msdx/gradle-publish/issues/13#issuecomment-252279905,
or mute the thread

**Comment by msdx** [comment]
欢迎你fork，然后来实现。这确实是多一种选择。只是我没有太多的精力花在这上面(被问过的问题有时候不仅仅是这个库上面的)，所以最后改成建议直接拷到项目中。

**Comment by msdx** [comment]
实际上你的思路更适合把它改写为一个高度封装的插件，属性配置改为在自定义的DSL中设置，它会更灵活也更直观简洁。
