### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by CarGuo** [msdx/gradle-publish#15]
你好，现在bintray是收费吗？请问下现在您这边还有在使用吗？bintray使用过期后会怎么样？
![image](https://cloud.githubusercontent.com/assets/10770362/20950794/cf507d48-bc5c-11e6-8654-43edb9176c1e.png)

**Comment by msdx** [comment]
我用的是免费的。目前没收到收费的提示或通知。

**Comment by CarGuo** [comment]
谢谢，应该是我选择了付费的
