### ISSUE TITLE
有报错信息

### ISSUE THREAD

**Issue by iceuncle** [msdx/gradle-publish#17]
HTTP/1.1 404 Not Found [message:Repo 'maven' was not found

**Comment by msdx** [comment]
您可能需要登录bintray并创建一个maven repo

**Comment by iceuncle** [comment]
新建了一个仓库，并改掉了repo。但是有新的报错。我开着翻墙的。
 java.net.SocketException: Operation timed out (Read failed)

**Comment by msdx** [comment]
网络不通。可能是被墙了，你试着代理一下

**Comment by msdx** [comment]
网络不通。可能是被墙了，你试着代理一下

**Comment by iceuncle** [comment]
好吧，虽然报错了，但是我发现库已经发布到 bintray上了。多谢了！

**Comment by iceuncle** [comment]
需要运行gradlew install ，然后运行gradlew bintrayUpload。
