### ISSUE TITLE
关于提交aar

### ISSUE THREAD

**Issue by jymot** [msdx/gradle-publish#2]
你好，我的aar里面依赖了第三方aar，那么在其他项目里面依赖我push到jcenter的aar后，并没有关联上我aar里面依赖的第三方aar，请问这个需要怎么做？

**Comment by msdx** [comment]
查了一下国外的一些论坛，原因似乎是java插件的依赖，maven-publish插件会把它们添加到pom文件当中，而android插件的依赖则不会。具体原因没查。
已找到解决方法，稍后更新一下。

**Comment by msdx** [comment]
上面方法参考自：http://stackoverflow.com/questions/24743562/gradle-not-including-dependencies-in-published-pom-xml。

**Comment by jymot** [comment]
学习了，谢谢
