### ISSUE TITLE
本地环境java8怎么办

### ISSUE THREAD

**Issue by ohmerhe** [msdx/gradle-publish#3]
我的本地环境java8，javadoc会出错

**Comment by msdx** [comment]
@ohmerhe 请贴一下日志

**Comment by ohmerhe** [comment]
23:58:10.740 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/javadoc''
23:58:11.330 [ERROR] [system.err] javadoc: error - Illegal package name: "/Users/ohmer/Projects/Android/AndroidEX/library/src/main/kotlin/com/kotlinthree/andex/StringEX.kt"
23:58:11.330 [ERROR] [system.err] javadoc: error - Illegal package name: "/Users/ohmer/Projects/Android/AndroidEX/library/src/main/kotlin/com/kotlinthree/andex/res/ResourceEX.kt"
23:58:11.330 [ERROR] [system.err] javadoc: error - Illegal package name: "/Users/ohmer/Projects/Android/AndroidEX/library/src/main/kotlin/com/kotlinthree/andex/widget/ToastEX.kt"
23:58:11.351 [QUIET] [system.out] 3 errors
23:58:11.364 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
23:58:11.365 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/javadoc'' finished with exit value 1 (state: FAILED)

和kotlin代码有关吗？不过我把你的options的配置删掉就好了

**Comment by msdx** [comment]
你的源文件都是utf8的吗

**Comment by ohmerhe** [comment]
当然，这个不会有问题

**Comment by msdx** [comment]
@ohmerhe 我这边还没试过使用kotlin导出javadoc，LOG上看好像是和kotlin有关。不过我options里主要做的是设置编码方式以及链接到java官方文档中。这个可能暂时处理不了。
另外，问一下，去掉options之后，生成的文档，打开后默认字符集下中文会乱码吗？

**Comment by ohmerhe** [comment]
不会乱码

**Comment by msdx** [comment]
@ohmerhe 好吧。那这条issue我可以关了吗？
如果有关于项目的改进，欢迎提交PR。

**Comment by ohmerhe** [comment]
恩，关了吧
