### ISSUE TITLE
可以试试这种方式：http://www.tuicool.com/articles/UFzmuiY。

### ISSUE THREAD

**Issue by gzu-liyujiang** [msdx/gradle-publish#4]
在Android Studio 2.0 Preview4上按你的教程来，报错：Error:Could not find property 'android' on task ':sourcesJar'.。
后来找到这种方式，感觉这种方式似乎更简洁：http://www.tuicool.com/articles/UFzmuiY。

**Comment by msdx** [comment]
@gzu-liyujiang 你的gradle 以及gradle android plugin版本是多少？

**Comment by msdx** [comment]
如果你仔细对比，你就会发现，除了对javadoc进行了编码标题链接等配置，发布于bintray的过程与你所发的文章是一样的，至于我后面的那段配置是用于发布SNAPSHOT版本到jforg.com上的

**Comment by msdx** [comment]
@gzu-liyujiang 如果你的问题已经解决，那我先把这个issue关了？

**Comment by gzu-liyujiang** [comment]
谢谢，问题已解决
