### ISSUE TITLE
SONATYPE_KEY是什么

### ISSUE THREAD

**Issue by tandengzhao** [msdx/gradle-publish#9]
不好意思，麻烦问一下，SONATYPE_KEY 这个是 GPG 的密码还是什么

**Comment by msdx** [comment]
这个是用于提交到maven上的，可不填。
现在用的这个脚本来源于公司项目，提交到maven的功能我自己没试，一直只用于提交到bintray上。

**Comment by msdx** [comment]
已移除mavenCentralSync配置。
